Upgrade AWS provider and VPC module (#129)
AWS just introduced private link for S3:
https://aws.amazon.com/ru/blogs/aws/aws-privatelink-for-amazon-s3-now-available/

This currently breaks Terraform with the following error message:
Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

More on this issue here:
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/445

Tested that this upgrade doesn't force a rebuild of the infrastructure.