Use short prefix for domains in route53
Using regular prefix causes:
Error: Error requesting certificate: InvalidDomainValidationOptionsException: The first domain name can be no longer than 64 characters.